# Adapted from Gui Brando's Makefile (Hans A. Winther's FML LPT example)
# for the Intel oneAPI toolchain used to build (MG-)GLAM on Cosma8:
#   module purge; module load intel_comp/2024.2.0 compiler-rt tbb compiler mpi
# Cosma8 is AMD EPYC (Zen2): use -march=core-avx2, never -x* flags.

SHELL := /bin/bash

#===================================================
# Set c++17 compliant compiler. If USE_MPI we use MPICC
#===================================================

CC    = icpx    -std=c++17 -O3 -Wall -Wextra -march=core-avx2 -DGADGET_LONG_INT_IDS
MPICC = mpiicpx -std=c++17 -O3 -Wall -Wextra -march=core-avx2 -DGADGET_LONG_INT_IDS

#===================================================
# Options
#===================================================

# Use MPI
USE_MPI          = true
# Use OpenMP threads
USE_OMP          = true
# Use the FFTW library
USE_FFTW         = true
# Use threads in FFTW
USE_FFTW_THREADS = false
# Use the GSL library (Spline, ODESolver)
USE_GSL          = true
# Log allocations in the library
USE_MEMORYLOG    = true
# Check for bad memory accesses
USE_SANITIZER    = false
# Print more info as the code runs and do some more checks
USE_DEBUG        = true
# hdf5
USE_HDF5         = false
# Use LUA (required to use parameterfile)
USE_LUA          = true

#===================================================
# Include and library paths
#===================================================

# Main library include (path to folder containing FML/)
FML_INCLUDE    = /cosma8/data/dp203/dc-ruan1/mgglam_claude/MG-GLAM/2LPTIC_Gui/FML

# GSL : only needed if USE_GSL = true
GSL_INCLUDE    = /cosma/local/gsl/2.7.1/include
GSL_LIB        = /cosma/local/gsl/2.7.1/lib
GSL_LINK       = -lgsl -lgslcblas -Wl,-rpath,$(GSL_LIB)

# FFTW : built for intel_comp/2024.2.0 + intel_mpi 2024.2.0 (epyc build)
FFTW_INCLUDE   = /cosma/local/fftw/intel_2024.2.0_intel_mpi_2024.2.0/3.3.10-epyc/include
FFTW_LIB       = /cosma/local/fftw/intel_2024.2.0_intel_mpi_2024.2.0/3.3.10-epyc/lib
FFTW_LINK      = -lfftw3 -Wl,-rpath,$(FFTW_LIB)
FFTW_MPI_LINK  = -lfftw3_mpi
FFTW_OMP_LINK  = -lfftw3_omp

# LUA (Gui Brando's public install; static liblua.a)
LUA_INCLUDE    = /cosma/apps/dp203/dc-bran2/lua-5.4.0/install/include
LUA_LIB        = /cosma/apps/dp203/dc-bran2/lua-5.4.0/install/lib
LUA_LINK       = -llua -ldl

#===================================================
# Compile up all library defines from options above
#===================================================

INC     = -I$(FML_INCLUDE)
LIB     =
LINK    =
OPTIONS =

ifeq ($(USE_MPI),true)
CC	 = $(MPICC)
OPTIONS += -DUSE_MPI
endif

ifeq ($(USE_OMP),true)
OPTIONS += -DUSE_OMP
CC      += -fopenmp
endif

ifeq ($(USE_SANITIZER),true)
CC      += -fsanitize=address
endif

ifeq ($(USE_GSL),true)
OPTIONS += -DUSE_GSL
INC     += -I$(GSL_INCLUDE)
LIB     += -L$(GSL_LIB)
LINK    += $(GSL_LINK)
endif

ifeq ($(USE_LUA),true)
OPTIONS += -DUSE_LUA
INC     += -I$(LUA_INCLUDE)
LIB     += -L$(LUA_LIB)
LINK    += $(LUA_LINK)
endif

ifeq ($(USE_FFTW),true)
OPTIONS += -DUSE_FFTW
INC     += -I$(FFTW_INCLUDE)
LIB     += -L$(FFTW_LIB)
ifeq ($(USE_MPI),true)
LINK    += $(FFTW_MPI_LINK)
endif
ifeq ($(USE_OMP),true)
ifeq ($(USE_FFTW_THREADS),true)
OPTIONS += -DUSE_FFTW_THREADS
LINK    += $(FFTW_OMP_LINK)
endif
endif
LINK    += $(FFTW_LINK)
endif

ifeq ($(USE_MEMORYLOG),true)
OPTIONS += -DMEMORY_LOGGING
endif

ifeq ($(USE_HDF5),true)
OPTIONS += -DUSE_HDF5
INC     += -I$(HDF5_INCLUDE)
LIB     += -L$(HDF5_LIB)
LINK    += $(HDF5_LINK)
endif

#===================================================
# Object files to be compiled
#===================================================

VPATH = $(FML_INCLUDE)/FML/Math/:$(FML_INCLUDE)/FML/Global/:$(FML_INCLUDE)/FML/GadgetUtils/:$(FML_INCLUDE)/FML/FileUtils/:$(FML_INCLUDE)/FML/ODESolver/:$(FML_INCLUDE)/FML/Spline/:$(FML_INCLUDE)/FML/ParameterMap/
OBJS = Main.o Global.o GadgetUtils.o ODESolver.o Spline.o Math.o ParameterMap.o

TARGETS := test
all: $(TARGETS)
.PHONY: all clean

clean:
	rm -rf $(TARGETS) *.o

test: $(OBJS)
	${CC} -o $@ $^ $(OPTIONS) $(LIB) $(LINK)

%.o: %.cpp
	${CC} -c -o $@ $< $(OPTIONS) $(INC)
